### ISSUE TITLE
Cannot open settings

### ISSUE THREAD

**Issue by florian-lefebvre** [volta-net/feedback#1]
When clicking on my profile picture and then Settings, it opens an empty modal.
```bash
There are no focusable elements inside the <FocusTrap />
TypeError: Cannot read properties of undefined (reading 'owner')
```

**Comment by benjamincanac** [comment]
Hello @florian-lefebvre,

Indeed, this modal is only used for repositories settings at the moment. We should not display the button when a user has no repositories yet.

Thanks for your feedback!

**Comment by benjamincanac** [comment]
The settings modal has been updated in latest update! Thanks again! :)
