### ISSUE TITLE
Update icon on MacOS (PWA) for consistency

### ISSUE THREAD

**Issue by mcfarljw** [volta-net/feedback#102]
It's a very minor issue but when installing the app as a PWA on MacOS the icon doesn't match the style of other installed apps making it a bit of an eyesore. If there is a way it's be great if an icon that matches the style of other apps could be used on MacOS specifically.

![Google Chrome 2024-08-01 at 07.17.04.png](https://volta.s3.fr-par.scw.cloud/Google_Chrome_2024_08_01_at_07_17_04_8cc1697a0a.png)

**Comment by benjamincanac** [comment]
Why don't you use the Mac app? https://volta.net/download

**Comment by mcfarljw** [comment]
I didn't know there was a Mac app, I will use that instead. It's been awhile, so I think last time I checked their was only a PWA.
