### ISSUE TITLE
Missing commits and status checks inside PRs

### ISSUE THREAD

**Issue by mirkopoloni** [volta-net/feedback#13]
I read in the changelog that inside the PRs activities feed there should be the possibility to see the commits and status checks.

> Issues and pull requests activities feed was already well fed, but to make it as close as possible to GitHub's issue page, we've added commits and corresponding status checks. You can now also see directly from the issue details if a pull request CI has failed with a link to GitHub.

I can't see them, do I need to do something to activate them?

**Comment by benjamincanac** [comment]
Hello @mirkopoloni,

Commits and status checks on pull requests are not imported by default, you will only see new ones. This choice was made to ensure repositories imports wouldn't take days.

Let me know if new workflow runs don't appear on your pull requests.

**Comment by mirkopoloni** [comment]
Hello @benjamincanac,

This makes sense. I will check it and let you know if it won't work.
I'll close this, thanks 😄
