### ISSUE TITLE
Dropdown menu for swimlane header renders incorrect UI

### ISSUE THREAD

**Issue by sean-perkins** [volta-net/feedback#14]
Clicking the "..." button in the header of a swimlane results in broken UI. 

<img width="393" alt="Screen Shot 2022-10-21 at 1 09 55 PM" src="https://user-images.githubusercontent.com/13732623/197251235-adfcf930-37ee-4655-9f83-8683efe5e196.png">

It appears to be rendering the icon name "octicon-eye-closed-24" as text instead of as an icon.

**Comment by sean-perkins** [comment]
This appears to have been resolved (either from an over-the-air update) or the result of a reload of the view. 
<img width="618" alt="Screen Shot 2022-10-21 at 1 38 40 PM" src="https://user-images.githubusercontent.com/13732623/197256140-fc0dee57-db51-48f1-b185-4dea1fe1ad4c.png">

**Comment by benjamincanac** [comment]
Might have been a network issue when loading the icon. I'll keep in mind if this happens again.

Thanks for the feedback! 😊
