### ISSUE TITLE
`Delete notification` button is super super far to the right

### ISSUE THREAD

**Issue by derberg** [volta-net/feedback#15]
Hey.

When I read notifications, sometimes, when clicking on notification, I already know it is not relevant for me, that I can just remove it. But the problem is that I have to move far to the right on large screen to the delete button.

Would be nice to have `delete` 🗑️ icon on a notification card

**Comment by benjamincanac** [comment]
Hello @derberg,

Have you tried using keyboard shortcuts? You can press `d` to quickly delete a notification and `u` to mark it as read / unread.

You can view the full list of shortcuts by pressing `?`.

**Comment by derberg** [comment]
OMG OMG OMG!!! shortcuts ❤️ 

@benjamincanac thanks mate!!! you definitely need to promote these more in the UI. Like for example when I hover over `Delete notification`, there could ba a tooltip saying "dude, start using shortcuts" or stuff like that 😄

**Comment by benjamincanac** [comment]
Indeed, we're working on it at this moment, every button with a shortcut will have its tooltip 😊
