### ISSUE TITLE
Have some kind of permament filters and actions

### ISSUE THREAD

**Issue by derberg** [volta-net/feedback#16]
Hey.

I like that I can quickly click on "tag" to apply fast filter, and then delete all notifications with one click.

What I'm missing is to "persist" this action. I get a lot of notifications related to "bot" activity. I want them to be removed by default.

I hope it makes sense

**Comment by benjamincanac** [comment]
Hello @derberg,

We already have this planned in our roadmap, you'll be able to save your current filters under a name.

This should be available in the coming weeks.

**Comment by benjamincanac** [comment]
Hello @derberg,

We've just released a new [v1.4.0](https://volta.net/changelog/v1.4.0) version with advanced filters. You can also read more about it the newest [documentation](https://volta.net/docs/search/filters).

Let me know if this works for you!
