### ISSUE TITLE
Missing style on links

### ISSUE THREAD

**Issue by Akryum** [volta-net/feedback#17]
Links in comments are indistinguishable from normal text until I mouseover them:

![image](https://user-images.githubusercontent.com/2798204/198077397-982629cb-bed9-4f24-8d21-409a3580d7fd.png)

**Comment by benjamincanac** [comment]
Hello @Akryum,

This is really strange, we changed the color of links in markdown from blue to white but those should be bold. What browser are you using?

**Comment by Akryum** [comment]
Firefox on a loDPI screen.
Bold for link is a bit strange, maybe blue like on GitHub is better.

**Comment by benjamincanac** [comment]
@Akryum I agree with you, links will be reverted to blue in the next release!
