### ISSUE TITLE
github issue comments is display other account comments on volta

### ISSUE THREAD

**Issue by kazupon** [volta-net/feedback#18]
### github issue comment:
https://github.com/nuxt-community/i18n-module/issues/1568#issuecomment-1290783373

### volta 
<img width="1850" alt="image" src="https://user-images.githubusercontent.com/72989/198859705-4268f26b-070b-48c8-98a8-e274d42294fc.png">

**Comment by kazupon** [comment]
I'm seeing some issue on another github issue comment:

### comment on github issue
https://github.com/nuxt-community/i18n-module/issues/1591#issuecomment-1298551577

### comment on volta
<img width="1298" alt="volta-issue1" src="https://user-images.githubusercontent.com/72989/199370410-d7c655a2-0940-404d-a80b-567066422489.png">

**Comment by benjamincanac** [comment]
@kazupon Thank you for reporting this, it should be fixed in the next release!

**Comment by kazupon** [comment]
Thanks!
I am happy this issue help you :)

**Comment by benjamincanac** [comment]
This should have been solved in latest release, let me know if you still encounter the issue.
