### ISSUE TITLE
Feature Request: kanban workflow status visiblity for outside member

### ISSUE THREAD

**Issue by kazupon** [volta-net/feedback#19]
The volta workflow status is visible only to members who are using volta.
It would be good if the general public could see what the status is.

I don't know how to achieve this, as one idea, would be to use GitHub labels.

**Comment by benjamincanac** [comment]
Hello @kazupon,

This is a nice timing, we just released [v1.3.0](https://volta.net/changelog/v1.3.0) with a board embed feature, also anyone on Volta can view public repositories now. 

Does this solve your issue?

**Comment by kazupon** [comment]
Oh! I've just saw the v1.3.0 volta!
That's pretty good!
Thanks!
