### ISSUE TITLE
`G` shortcut to open issue/pr in GitHub do not work

### ISSUE THREAD

**Issue by derberg** [volta-net/feedback#20]
I tried the keyboard shortcut to open the link in GH, as finding the right button is annoying, but it doesn't work.

`d` and `command + d` works like a charm, but `command + g` is not.

**Comment by benjamincanac** [comment]
Hello @derberg,

Are you trying to do `⌘+G` from the inbox? Are you on MacOS? A little note, this shortcut won't work if you're focused in a textarea, when writing a new comment for example.

**Comment by derberg** [comment]
I'm in `inbox`, focused on inbox, MacOS, and on brave browser. Other filters work

![Screenshot 2022-11-09 at 11 47 13](https://user-images.githubusercontent.com/6995927/200810450-316cc3b4-5a18-4ca4-873e-f6e5802bbb1a.png)

**Comment by derberg** [comment]
sorry, I forgot that something wasn't working for me right in brave and since last week I use firefox for volta 😅

**Comment by smarroufin** [comment]
Hello @derberg !

I've tested the `CMD+G` shortcut on Firefox. Indeed it tries to open a new tab, interpreted as pop-up by Firefox, which is disabled by default.
Firefox should notify you with a banner that the opening has been block, and allow you to enable pop-ups from volta.net. Isn't it the case?

**Comment by derberg** [comment]
omg, you are right, sorry about that. It was a firefox pop-up blocker indeed. Thanks!
