### ISSUE TITLE
Authenticate using Personal Access Token

### ISSUE THREAD

**Issue by jameslkingsley** [volta-net/feedback#22]
Right now Volta requires the user to install the Volta app on GitHub onto their chosen organisations. This requires the manager of the organisation to approve the install, and it grants access to everyone in the org to use Volta. You can select which repo's are accessible but this is not per-user.

I'm not sure if this is possible / compatible with how you're consuming GitHub's APIs, but it would be great if we could authenticate Volta using a Personal Access Token (https://github.com/settings/tokens). There's a new version of tokens as well that may be better to implement.

Using PATs would allow users to login on their own without the approval of org managers, and they would simply have access to the repos and tools already granted by the org. This means an org could disallow certain repos from a subset of their members and the PAT would respect this.

Hopefully this would just be a case of pasting in a token, bypassing the existing GitHub installation flow, and tweaking the authentication headers in requests.

**Comment by benjamincanac** [comment]
Hello @jameslkingsley,

First of all, thank you for your detailed suggestion. I understand that having to request an installation on an organization can be a pain.

However, when you install our GitHub app selected (or all) repositories are imported into Volta and kept up-to-date through webhooks, all the real-time synchronisation wouldn't be possible without this unfortunately.

I'm wondering, why would you want to prevent some members to access repositories on Volta they have access on GitHub? If an organization fine-tune the members permissions on GitHub, it will be reflected on Volta.
