### ISSUE TITLE
Clicking on a disabled button on the Board still triggers still goes to the card

### ISSUE THREAD

**Issue by posva** [volta-net/feedback#29]
The button is disabled but clicking it still triggers the card click

![Screenshot 2022-11-18 at 10.54.14.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2022_11_18_at_10_54_14_5942a08467.png)

**Comment by benjamincanac** [comment]
Indeed, this should not be the case, thank for the feedback 😊
