### ISSUE TITLE
Some cards cannot be moved to other columns

### ISSUE THREAD

**Issue by posva** [volta-net/feedback#30]
![Screenshot 2022-11-18 at 10.56.05.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2022_11_18_at_10_56_05_9628ed38fe.png)

I can't move these cards to other columns but I don't know if this is a bug or if it is expected. In which case it would be helpful to differentiate them visually from other cards and have some description on hover maybe?

**Comment by benjamincanac** [comment]
Hello @posva,

Indeed, pull requests that are linked to an issue are locked to the `Triage` column to as you should already see the issue in the `In Review` column. We should indeed add something to explain this behaviour. Although you can still drag them vertically to reorder.

As a note, there is also a setting you can access by pressing `,` to hide tholinked pull requests

**Comment by posva** [comment]
aah, I see, it makes sense. It's curious they are hidden by default on desktop but not on the browser

**Comment by posva** [comment]
I think I just enabled it thinking it was something else and settings are not synced 😆

**Comment by benjamincanac** [comment]
Yes this setting is not synced and is only stored in local storage, also in the next release this will be set to `true` by default.
