### ISSUE TITLE
Filtering with a label present on multiple repos

### ISSUE THREAD

**Issue by ChristopheCVB** [volta-net/feedback#34]
Filtering with a label that is present on multiple repos doesn't work
https://volta.s3.fr-par.scw.cloud/Filter_Label_0d8d8a7529.mp4

**Comment by benjamincanac** [comment]
Hello @ChristopheCVB,

We just released a new [v1.4.0](https://volta.net/changelog/v1.4.0) version with advanced filters so it might fix the issue.

I couldn't reproduce myself but let me know if you still encounter this bug.

**Comment by ChristopheCVB** [comment]
@benjamincanac In fact, I just misunderstood what the base Board is displaying. I thought it was displaying everything from all repos, but it's not. As @smarroufin explained to me that some filters were applied to not clog that view.

**Comment by benjamincanac** [comment]
Indeed, is the behaviour of the board relevant for you?

**Comment by ChristopheCVB** [comment]
Totally forgot to get back to you with this. Now that I know how it works, yes ;)
