### ISSUE TITLE
Understanding notifications

### ISSUE THREAD

**Issue by derberg** [volta-net/feedback#35]
I'm not 100% sure I understand notifications. 
At the beginning I understood `Inbox` as a place where I get all notifications, just like I was getting to my mailbox. But I think it is not the case. I'm for example watching https://github.com/asyncapi/bundler for all activities, but when there is a new issue created like https://github.com/asyncapi/bundler/issues/97 I do not get notifications in `Inbox` really.

This is what I have in my settings now 👇 What should I change/update, what is recommended?
![Screenshot 2022-11-22 at 10.19.28.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2022_11_22_at_10_19_28_015c39c319.png)

**Comment by ChristopheCVB** [comment]
Check https://volta.net/volta-net/feedback/issues/2

**Comment by derberg** [comment]
@ChristopheCVB sorry but I don't get how it relates. The issue you linked, I actually saw it before creating new issue, but it is talking about the overload of notifications, and in my case, it is about missing notifications.

If I understand correctly, notifications work per repo. In one repo I can say watch or not, maybe ignore, or mentions only. 
So in the repo that I provided as example, I'm watching all, meaning I'm `Engage`.

**Comment by benjamincanac** [comment]
@derberg Unfortunately, we've made our own subscriptions system so they are not synced with GitHub. By default you're on the `Watch` preset for all repositories. You can configure your repositories presets for all your organizations quickly from the Settings by pressing `,`.

You can read more on repositories subscriptions in our newest [documentation](https://volta.net/docs/repository/subscriptions).

**Comment by derberg** [comment]
yeah, that's not bad, just not intuitive, would be good to clear it out during setup as for me it was natural that you will just reuse GitHub.

what about repositories in profiles/organizations where I'm not present? For example I am involved in discussions in this issue, but I do not get notification when you reply, which I think is wrong. How can I enable it?

**Comment by benjamincanac** [comment]
We might need to be more clear in the welcome step dedicated to subscriptions indeed.

Public repositories you're not a maintainer of are only accessible since _v1.3.0_ and notifications are disabled for now, we still have some work to do to enable them but it should be ready in the next release! You can read more about it in the [changelog](https://volta.net/changelog/v1.3.0#public-repositories).
