### ISSUE TITLE
More flexible issue lookup through `#`

### ISSUE THREAD

**Issue by posva** [volta-net/feedback#38]
when writing _Duplicate of #_ and similar, the autocompletion after the `#` stops if a space in entered but this limits the search quite a lot. On GitHub you can still type after the space

![Screenshot 2022-11-24 at 17.10.37.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2022_11_24_at_17_10_37_795308873a.png)

**Comment by benjamincanac** [comment]
@posva Indeed, we should support this! We also plan to support the duplicate mention like on GitHub!
