### ISSUE TITLE
Switch to inbox view on a repository view

### ISSUE THREAD

**Issue by stafyniaksacha** [volta-net/feedback#4]
Would be great to have quick access to a filtered inbox view from a repository
<img width="950" alt="image" src="https://user-images.githubusercontent.com/3911343/194755221-4b95d16f-1655-4556-82da-8a7991412429.png">

**Comment by benjamincanac** [comment]
Hello @stafyniaksacha,

Have you tried clicking on the `2` badge next to `nuxt-toaster`? In next update, this badge will also be available for organizations when collapsed.

Let me know if this solve your issue :)

**Comment by stafyniaksacha** [comment]
That's exactly what was looking for :) 
Thanks! 

Maybe a simple `title="view inbox"` can help for new users?

**Comment by benjamincanac** [comment]
Great idea, this will be added in next release.

Thanks for your feedback! 🙂
