### ISSUE TITLE
Tag releases in private repositories appear despite not having a plan for private repositories

### ISSUE THREAD

**Issue by posva** [volta-net/feedback#43]
Elk published a few tags and I received quite a few notifications even though I do not have access to other notifications for the repository (it's private)

**Comment by benjamincanac** [comment]
@posva Don't you have a subscription to Volta? Do you mean you received a notification about a new release? Are you subscribed to this repository?

**Comment by posva** [comment]
Sorry I wasn't clear:

- I don't have a subscription
- I haven't changed the watch settings for Elk so they are on "Watch"
- I only received release notifications
- The Elk team probably uses Volta

I imagine the release notification shouldn't happen unless I have a paid subscription, that's what I meant

**Comment by benjamincanac** [comment]
Indeed, we didn't put any restriction on notifications for private repositories yet, we'll have to think about that! The only way you can solve this for now is to access the repository through the url and select the `Ignore` preset.

Thanks for pointing that out!
