### ISSUE TITLE
Periodic sync for deleted issues

### ISSUE THREAD

**Issue by XenBG** [volta-net/feedback#45]
As an admin I can delete any issue. If this issue has already been fetched by Volta, after I delete it from GitHub, it still appears on Volta.

When I try to sync the whole repository again, the deleted issues disappears from Volta, so the problem is maybe related to data caching.

**Comment by madebyfabian** [comment]
Would be great if that could be fixed. It's also for when you load a repo for the first time, it will sync also deleted issues. For large repos, that's a nightmare since you cannot "hide" an issue from your volta UI and therefore you always have to remember which issues of those displayed are really existing anymore.

**Comment by benjamincanac** [comment]
Indeed, we were missing a hook when an issue was deleted, this has been fixed and will be available in tomorrow's release. Syncing the whole repository did remove deleted issues as we make a diff with GitHub.

Thanks for the report!

**Comment by madebyfabian** [comment]
@benjamincanac When I loaded nuxt/nuxt for the first time in volta, it displayed some issues that were no longer available on GitHub (deleted, not closed). But maybe this was just a bug and was an old issue from nuxt/framework that has not been transfered successfully. Will check if I find an example to reproduce this.

**Comment by benjamincanac** [comment]
@madebyfabian I guess this has to do with the fact that we missed some `issues:deleted` hooks, this should not happen again and a full sync of the repository should fix it.

Feel free to open a new issue if you encounter the bug again 😊
