### ISSUE TITLE
LogRocket session exceed quota

### ISSUE THREAD

**Issue by Barbapapazes** [volta-net/feedback#48]
Hello,

Just opened the console (from volta) and I see this message

![image](https://user-images.githubusercontent.com/45267552/214339800-2c75a826-841a-4742-9b85-851f766e5569.png)

**Comment by benjamincanac** [comment]
@Barbapapazes This is not really an issue, we've downgraded LogRocket as it's really expensive. However, we kept it for the 500 free sessions so it disables itself once the quota is exceeded.

**Comment by Barbapapazes** [comment]
Effectively, not really an issue but I see it so I've just report it! But you can close it!

**Comment by benjamincanac** [comment]
You might not know, but you can report feedback directly from within Volta by clicking on the `Help & Feedback` at the bottom of the sidebar 😊

**Comment by Barbapapazes** [comment]
Hooo I did not notice this! Thanks!
