### ISSUE TITLE
Can remove labels or assignees (just UI not in DB)

### ISSUE THREAD

**Issue by Barbapapazes** [volta-net/feedback#49]
Hello,

From the inbox, when I receive a message, I can change properties of the issue.

Imagine you post an issue in a repo where you're not a writer or a maintainer, then, someone respond, you receive a message in your inbox.

Like this.

![image](https://user-images.githubusercontent.com/45267552/214801415-ae4f60a7-091b-4700-9bff-b0b0f04153ee.png)

But, using the UI, I'm able to date, labels or assignees.

Before

![image](https://user-images.githubusercontent.com/45267552/214801515-0930e9e8-efde-442b-b5af-a992e6df0982.png)

After

![image](https://user-images.githubusercontent.com/45267552/214801600-fa8d4217-68de-47eb-9202-9092b5c0c905.png)

This will not be reflected in DB and I can only remove. (there is a forbidden logo when I hover `add` from labels or assignees.

**Comment by benjamincanac** [comment]
Hello @Barbapapazes,

Thanks for your feedback! 😊 

We've fixed this already, it won't happen anymore in the next release on next Tuesday.
