### ISSUE TITLE
Repository still in pending state

### ISSUE THREAD

**Issue by stafyniaksacha** [volta-net/feedback#5]
When installing, we've set up a lot of repositories and some of those still are in pending state:

<img width="119" alt="image" src="https://user-images.githubusercontent.com/3911343/194768313-c2a104d1-cedf-4542-af40-833ab85c8778.png">

That would be great to be able to manually retrigger the sync from volta.

Also, if you are interested, we can re-run the installation from scratch to check the process.

**Comment by benjamincanac** [comment]
Hey @stafyniaksacha,

Actually you can re-sync manually from Volta, if you go to your repository you can access its settings. In `Members` and `GitHub`, you can trigger the sync yourself.

![CleanShot 2022-10-09 at 19.05.37@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2022_10_09_at_19_05_37_2x_e0edf8f112.png)

However this shouldn't be happening. It seems we have some repositories that were installed some time ago stalling. I will take a look at this and trigger the sync for all concerned repositories, thanks for pointing this out! 🙂

**Comment by benjamincanac** [comment]
All pending repositories should have been imported, can you confirm?

**Comment by mechelon** [comment]
I'm afraid the problem still persists. None of my repos has synced so far, and it's like that for about an hour or so. I also tried the manual sync, but it did not change anything. I really want to give this a try but I wasn't able to see any issue so far :( 

![CleanShot 2022-10-19 at 16 13 26@2x](https://user-images.githubusercontent.com/26432041/196716156-581c2e86-3df5-4253-9ec5-442b3238d90c.png)

**Comment by benjamincanac** [comment]
Hello @mechelon, 

Sorry for the inconvenience, we've had hundreds of people subscribing and installing their repositories (10k+) at the same time, so it might take a while. Your repositories have been queued and will import in order.

Thank your for your patience.

**Comment by benjamincanac** [comment]
Everyone should now have access to their repositories, we successfully imported more than 40k repositories 🎉
