### ISSUE TITLE
Web - Cors Issue / Not loading

### ISSUE THREAD

**Issue by harlan-zw** [volta-net/feedback#50]
- visited inbox, nothing loads (this is after waiting a couple of min)
![image.png](https://volta.s3.fr-par.scw.cloud/image_3aca2a2b39.png)

- went to nuxt/nuxt client side navigation (seems to be hanging forever)
![image.png](https://volta.s3.fr-par.scw.cloud/image_0f15f22dfe.png)

- refresh the page and it loads, but can't see any issues
- got an error toast

![image.png](https://volta.s3.fr-par.scw.cloud/image_a7ae8c6e71.png)

**Comment by harlan-zw** [comment]
Error from the toast

> Access to fetch at 'https://api.volta.net/repositories/nuxt/nuxt/issues' from origin 'https://volta.net/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by harlan-zw** [comment]
seems like it loaded after like 10 min

![image.png](https://volta.s3.fr-par.scw.cloud/image_d4ca84d003.png)

possibly because nuxt/framework -> nuxt/nuxt was syncing

would be cool if there was some UI element for if it's trying to sync

**Comment by benjamincanac** [comment]
Hello @harlan-zw,

Sorry for the late answer, we've had some trouble with repositories having lots of issues but we've made some improvements lately.

Do you still have the issue?

**Comment by harlan-zw** [comment]
Nope, this solved itself :) I think there was an issue here where I hadn't re-synced nuxt since it moved between repos

**Comment by benjamincanac** [comment]
@harlan-zw I remember there was a chaotic period when Daniel transferred all issues from `nuxt/framework` to `nuxt/nuxt`, this might have been the reason.
