### ISSUE TITLE
[Bug] Editing an issue description, saving it, the read-view is still the old one

### ISSUE THREAD

**Issue by madebyfabian** [volta-net/feedback#51]
When updating an issue description and saving it, the read view is still in the state before the change.

**Comment by benjamincanac** [comment]
@madebyfabian We've made some changes to the issue edition in the latest release and the whole draft system, this should not happen again. Can you let me know if you still have the bug?

**Comment by madebyfabian** [comment]
@benjamincanac Nice, now it seems to work perfectly! Thank you!
