### ISSUE TITLE
Add loading states

### ISSUE THREAD

**Issue by madebyfabian** [volta-net/feedback#55]
Currently, when visiting nuxt/nuxt with volta, there is a good amount of 10-15 seconds where you just have a blank page as there were no issues. Then suddently, they all pop up. So in general, if loading takes longer than 300ms, I would suggest to add spinners.

**Comment by madebyfabian** [comment]
Sorry for the issue spam here, I just really think volta has great potential, but currently I have so many bugs/wierd behaviour I'm not sure if it's fair to create so many bug reports, or if the project is just too early staged 😄.

**Comment by benjamincanac** [comment]
Don't be sorry, getting feedback is awesome!  We've added the loading state already, it will be available in tomorrow's release 😊 

However, we're still working to improve the loading time of repositories like `nuxt/nuxt` with so many issues. We'll fix that as soon as possible!

**Comment by madebyfabian** [comment]
@benjamincanac So great to hear 🙏🏻😊, looking forward to that release.
