### ISSUE TITLE
PWA briefly shows log in screen on initial open

### ISSUE THREAD

**Issue by mcfarljw** [volta-net/feedback#57]
I have installed the PWA on Android and via Chrome and when initially opening the app it briefly shows the log in screen even though I'm already logged in to the app. I've included a screen recording demonstrating the issue.

https://volta.s3.fr-par.scw.cloud/Screen_Recording_20230224_111733_Chrome_768542bda8.mp4

**Expected Result**
The splash screen or some other loading indicator is shown until the authentication state of the user is determined.

**Actual Result**
The user is briefly shown the the log in even when they are already logged in to an account.

**Comment by mcfarljw** [comment]
This also happens with the PWA when installed on a desktop using Chrome.

http://volta.s3.fr-par.scw.cloud/Screen_Recording_2023_02_24_at_11_41_30_AM_ad6b9106ca.mov

**Comment by benjamincanac** [comment]
@mcfarljw Thanks for the feedback, this should be fixed in the next release on Tuesday 😊
