### ISSUE TITLE
PWA shows not secure warning on top of screen

### ISSUE THREAD

**Issue by mcfarljw** [volta-net/feedback#58]
I'm seeing "Not Secure" when accessing https://volta.net/volta-net/feedback/issues/57 using the Chrome installed PWA.

![Screenshot 2023-02-24 at 11.44.08 AM.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2023_02_24_at_11_44_08_AM_2309d5cc38.png)

**Comment by Atinux** [comment]
Very weird, is it still happening?

**Comment by mcfarljw** [comment]
Yes, I'm also seeing it when opening the link to that issue using the latest stable version of Chrome. This usually happens because somewhere on the page `http` is being used instead of `https`. It looks like this is the case here as well with the MOV file in the comments (see highlighted section in screenshot).

![Screenshot 2023-03-22 at 11.32.04 PM.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2023_03_22_at_11_32_04_PM_ff8e827ed1.png)
![Screenshot 2023-03-22 at 11.33.15 PM.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2023_03_22_at_11_33_15_PM_ab2131ef3a.png)

**Comment by Atinux** [comment]
I guess we could force https for images and videos then.
