### ISSUE TITLE
Download for Windows

### ISSUE THREAD

**Issue by Intevel** [volta-net/feedback#6]
Currently, there is only a Download link for macOS, will there be windows version? Is there a release date?

**Comment by benjamincanac** [comment]
Hello @Intevel, 

I don't have an exact date for you but we are gonna release the application on Windows and Linux in the coming weeks.

**Comment by Intevel** [comment]
Sounds great ✅

**Comment by Intevel** [comment]
Maybe you publish a small PWA? @benjamincanac

**Comment by benjamincanac** [comment]
We have something almost ready for Windows, should be shipped next week. We're also considering making a PWA for mobile users or even using Capacitor, not sure yet.
