### ISSUE TITLE
Delete repositories

### ISSUE THREAD

**Issue by silvercent011** [volta-net/feedback#61]
Is there a plan to add a function to remove repositories from volta?

**Comment by benjamincanac** [comment]
Hello @silvercent011,

You can easily remove repositories from Volta by uninstalling our GitHub app. This will delete all related data.

**Comment by silvercent011** [comment]
Hi, @benjamincanac,

Thanks, it seems that have a delay time, i've uninstalled few hours ago and not worked. Looking now it's done.
