### ISSUE TITLE
New auto assignment of issues

### ISSUE THREAD

**Issue by derberg** [volta-net/feedback#64]
Hey there. Volta bot started auto-assigning people to issues if they open a PR linking to it. Is it intended? can this be disabled on app level? In our org we do not use `assign` feature and it is now kinda confusing.

examples:
- https://github.com/asyncapi/modelina/issues/1173#event-8947284331
- https://github.com/asyncapi/spec-json-schemas/issues/369#event-8972310792

**Comment by benjamincanac** [comment]
Hello @derberg,

Indeed, this was a feature that we implemented a long time ago but wasn't working, we fixed it last release.

I'm also quite unsure if this automation brings a lot of value here, we might disable it completely for now.

**Comment by derberg** [comment]
yeah, for us it is causing a lot of confusion now. Maybe for other not, so the best would be to have it "configurable", so I can opt-out

**Comment by benjamincanac** [comment]
It will be disabled on next Tuesday the time we make it configurable.
