### ISSUE TITLE
Swipe board with mouse

### ISSUE THREAD

**Issue by ojvribeiro** [volta-net/feedback#7]

**Comment by ojvribeiro** [comment]
Wow, nice! As a Trello user, the first thing I tried was swiping the board hehe.

**Comment by ChristopheCVB** [comment]
Isn't it already possible by clicking on the mouse wheel and moving the mouse left or right?

**Comment by ojvribeiro** [comment]
@ChristopheCVB I mean click and drag, just like you would do in a touch device. 😄

**Comment by ojvribeiro** [comment]
For instance, on Trello you can do this:

![Animação2](https://user-images.githubusercontent.com/8026741/203209886-ca229dc1-cb7e-44fe-9634-56d1f5f45403.gif)

**Comment by ojvribeiro** [comment]
Works like a charm! Thank you! ❤️
