### ISSUE TITLE
volta closing issues without warning

### ISSUE THREAD

**Issue by derberg** [volta-net/feedback#73]
please have a look at https://github.com/asyncapi/modelina/issues/749

we cannot figure why Volta bot closed that issue

there is a PR that was `Fixes` keyword, but the PR was merged not into default branch, but feature branch. And even if `fixes` keyword would trigger issue close it would be visible as the user owning PR did it, and not volta bot

**Comment by derberg** [comment]
just figured it was closed by https://github.com/asyncapi/modelina/pull/1141

**Comment by benjamincanac** [comment]
We've deployed a fix yesterday to prevent this from ever happening! A fix on the front-end will come on Tuesday to display missing linked activities.
