### ISSUE TITLE
Landing page performance issues in Safari

### ISSUE THREAD

**Issue by susickypavel** [volta-net/feedback#8]
Hi 👋,

This issue is regarding the landing page, which is performing poorly in Safari as it uses CPU for rendering the highly blurred square used as light. I'd suggest force GPU accelerated rendering of that layer using either transform trick or `will-change` property.

**Comment by susickypavel** [comment]
You are also animating the background-position property which causes continuous page repainting either you need to change the animation to animate optimized css properties such as transform or force the div to render in its layer. I'm not completely sure why only Safari is affected though. Here are stats from Activity Monitor.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/32848654/197880012-507d14b0-73cf-48a7-a7f0-dc41ccfff6fe.png">

I tried to set `will-change: filter` on the div that renders the blur and it worked (this forces the div to render in its own layer, so rest of the page is not affected), the load immediately decreased (see the increased GPU usage).

<img width="814" alt="image" src="https://user-images.githubusercontent.com/32848654/197880254-7ab0d246-167b-49ba-b614-9cd2f6f6374f.png">

**Comment by benjamincanac** [comment]
@susickypavel Thanks again for your details explanation, this should now be fixed as you suggested. Let me know if you still encouter the issue.

**Comment by susickypavel** [comment]
> @susickypavel Thanks again for your details explanation, this should now be fixed as you suggested. Let me know if you still encounter the issue.

I confirm it's now speedy ⚡️ Congratulations on 1.4.0 release!
