### ISSUE TITLE
Unable to archive data

### ISSUE THREAD

**Issue by Barbapapazes** [volta-net/feedback#80]
Hello,

When clicking on the button "archive", I've a forbidden error but I is my own repos.

![image](https://github.com/volta-net/feedback/assets/45267552/3429ced3-a390-41c1-be0f-de8db3f93aaa)

**Comment by benjamincanac** [comment]
Sorry about that! This should now be fixed 😊

**Comment by Barbapapazes** [comment]
Yes, fixed!
