### ISSUE TITLE
unsubscribed from a repo on github.com but still receiving on volta.net

### ISSUE THREAD

**Issue by Barbapapazes** [volta-net/feedback#83]
Hello,

Not sure how to explain this issue but let's try.

I was subscribe to a repo named `aneoconsulting/armonik.admin.gui`. Then, I completely ignore the repo using the system from GitHub.

But, in volta.net, I still received notifications when a new version is released and I don't know how to disable this.

**Comment by benjamincanac** [comment]
GitHub and Volta notification system is completely separate, which allows you to ignore Notifications on GitHub to handle on Volta instead. You can go to any repository and click the bell button on the top left of the header and select `Ignore`.

More on https://volta.net/docs/inbox/subscriptions

**Comment by Barbapapazes** [comment]
Yes but it's an external repo. I'm not a team member of `aneoconsulting`.

**Comment by Barbapapazes** [comment]
I've this and only this. No view of the repo.

![image](https://github.com/volta-net/feedback/assets/45267552/88b26baf-2609-46b2-8fd4-d64aeec2c33d)

**Comment by benjamincanac** [comment]
Do you mean you can't go to `https://volta.net/aneoconsulting/armonik.admin.gui` or find from the command menu?

**Comment by Barbapapazes** [comment]
Yes, I can't go to this URL.

![image](https://github.com/volta-net/feedback/assets/45267552/127195c6-f18c-4239-920b-491450d7eb37)

**Comment by Barbapapazes** [comment]
This is case sensitive.

https://volta.net/aneoconsulting/ArmoniK.Admin.GUI

**Comment by Barbapapazes** [comment]
But GitHub is not so I didn't thing about this possible issue to find the repo.

**Comment by Barbapapazes** [comment]
And now, I can disable notifications. Thanks!
