### ISSUE TITLE
Are milestones on Volta different from GitHub?

### ISSUE THREAD

**Issue by mcfarljw** [volta-net/feedback#89]
I have a bunch of milestones created on GitHub (without start/end dates) but don't see them on Volta. Are milestones separate on Volta or do they just require start/end dates? I looked through the https://volta.net/docs/get-started but wasn't able to find any additional details.

**Comment by benjamincanac** [comment]
Indeed, milestones are not synced with GitHub as they can be created on projects and don't have an `end_date` on GitHub. You can learn more about them here https://volta.net/docs/issue#properties

**Comment by mcfarljw** [comment]
Thanks for confirming and pointing me to relevant docs! Here is a little bit more about my thoughts and what I'm currently trying to do so just take it as feedback all with a grain of salt.

I am currently using several milestones on GitHub without either a `start_date` or `end_date` as a placeholder of issues for a not yet planned larger releases. I will then assign these dates later down the road.

I think it would make things feel a bit more connected if GitHub milestones did sync, could be associated with Volta projects, but if those properties aren't set just don't show up on the timeline. Of course I don't know the technical limitations so this just might not be feasible.

Having milestones and projects use the same terminology between GitHub and Volta but not be associated was a bit confusing for me.

**I think it's safe to close off this issue.**
