### ISSUE TITLE
Forks are not availables

### ISSUE THREAD

**Issue by Barbapapazes** [volta-net/feedback#96]
Hello,

In Volta, there is no way to have a repository that is a fork, even when this fork have been marked as accessible in the GitHub app configure panel

**Comment by benjamincanac** [comment]
Indeed, this was a decision we made at the beginning of the project to not include forks. Unfortunately, it's too late to change this setting as it would cause the import of thousand of repositories and saturate our servers 😬

**Comment by Barbapapazes** [comment]
Makes sens. Thanks for the response.
